language: python

python:
  - "3.6"
  - "3.7"


# command to install dependencies
install:
  - pip install .

# command to run tests
script: pytest

notifications:
  email:
    recipients:
      - jonas.rothfuss@gmail.com
    on_success: never
    on_failure: always